# Generated by Django 2.2 on 2021-02-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mattweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
